-- Generated from hospital.db for Vercel Postgres / Neon.
BEGIN;
DROP SCHEMA public CASCADE;
CREATE SCHEMA public;
SET search_path TO public;
CREATE TABLE "administracion_log" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "intervencion_id" integer,
  "fecha_envio" text,
  PRIMARY KEY ("id")
);

CREATE TABLE "caja_contenido" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "id_caja" integer NOT NULL,
  "instrumento" text NOT NULL,
  "cantidad" integer NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "cajas" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "nombre" text NOT NULL,
  "especialidad" text NOT NULL,
  "codigo_interno" text,
  "codigo_barras" text,
  "descripcion" text,
  "imagen" text,
  "fecha_caducidad" text,
  "ubicacion" text,
  "estado" text,
  "codigo_contenido" text,
  PRIMARY KEY ("id")
);

CREATE TABLE "cajas_instrumental" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "especialidad" text NOT NULL,
  "nombre_caja" text NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "ciclo_contenido" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "ciclo_id" integer NOT NULL,
  "caja_id" integer,
  "instrumento_id" integer,
  "cantidad" integer,
  PRIMARY KEY ("id")
);

CREATE TABLE "ciclos_contenido" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "ciclo_id" integer,
  "codigo_caja" text,
  PRIMARY KEY ("id")
);

CREATE TABLE "ciclos_esterilizacion" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "maquina_id" integer NOT NULL,
  "tipo_esterilizacion" text NOT NULL,
  "fecha_inicio" text NOT NULL,
  "fecha_fin" text,
  "estado" text NOT NULL,
  "usuario" text,
  "testigo_ok" integer,
  "incidencia" text,
  PRIMARY KEY ("id")
);

CREATE TABLE "ciclos_instrumental" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "ciclo_id" integer NOT NULL,
  "instrumental_id" integer NOT NULL,
  "fecha_caducidad" text,
  "ubicacion" text,
  PRIMARY KEY ("id")
);

CREATE TABLE "facultativos" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "nombre" text NOT NULL,
  "apellidos" text NOT NULL,
  "especialidad" text NOT NULL,
  "cnp" text NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "fichas_esterilizacion" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "tipo" text NOT NULL,
  "item_id" integer NOT NULL,
  "ciclo_id" integer NOT NULL,
  "maquina_id" integer NOT NULL,
  "tipo_esterilizacion" text NOT NULL,
  "fecha_inicio" text NOT NULL,
  "fecha_fin" text,
  "fecha_caducidad" text,
  "estado" text,
  "testigo_ok" text,
  "incidencia" text,
  "usuario" text,
  "ubicacion" text,
  "nombre_item" text,
  PRIMARY KEY ("id")
);

CREATE TABLE "formacion_contenido" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "intervencion_id" integer NOT NULL,
  "rol" text NOT NULL,
  "contenido" text NOT NULL,
  "imagen" text,
  PRIMARY KEY ("id")
);

CREATE TABLE "formacion_equipos" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "especialidad_id" integer NOT NULL,
  "nombre" text NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "formacion_especialidades" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "nombre" text NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "formacion_intervenciones" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "equipo_id" integer NOT NULL,
  "nombre" text NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "implantes_deposito" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "gtin" text,
  "referencia" text,
  "nombre" text,
  "lote" text,
  "caducidad" text,
  "lateralidad" text,
  "material" text,
  "especialidad" text,
  "fecha_entrada" text,
  PRIMARY KEY ("id")
);

CREATE TABLE "implantes_intervencion" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "intervencion_id" integer NOT NULL,
  "gtin" text NOT NULL,
  "descripcion" text NOT NULL,
  "numero_serie" text,
  "lote" text,
  "caducidad" text,
  "fabricante" text,
  "referencia" text,
  "tamano" text,
  "lateralidad" text,
  "material" text,
  "especialidad" text,
  PRIMARY KEY ("id")
);

CREATE TABLE "instrumental" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "caja_id" integer,
  "nombre" text NOT NULL,
  "descripcion" text,
  "imagen" text,
  "tipo" text,
  "especialidad" text,
  "codigo_operativo" text,
  "codigo_barras" text,
  PRIMARY KEY ("id")
);

CREATE TABLE "instrumental_old" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "caja_id" integer NOT NULL,
  "nombre" text NOT NULL,
  "descripcion" text,
  "imagen" text,
  "tipo" text,
  "especialidad" text,
  "codigo_operativo" text,
  "codigo_barras" text,
  PRIMARY KEY ("id")
);

CREATE TABLE "instrumental_suelto" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "nombre" text NOT NULL,
  "especialidad" text NOT NULL,
  "descripcion" text,
  "codigo_operativo" text,
  "codigo_barras" text,
  "ubicacion" text,
  "estado" text,
  PRIMARY KEY ("id")
);

CREATE TABLE "intervenciones" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "paciente_id" integer NOT NULL,
  "especialidad" text NOT NULL,
  "procedimiento" text NOT NULL,
  "facultativo_cnp" text NOT NULL,
  "fecha_intervencion" text NOT NULL,
  "zona_anatomica" text,
  "lateralidad" text,
  PRIMARY KEY ("id")
);

CREATE TABLE "maquinas_esterilizacion" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "nombre" text NOT NULL,
  "tipo" text NOT NULL,
  "codigo_interno" text,
  PRIMARY KEY ("id")
);

CREATE TABLE "pacientes" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "nuhsa" text NOT NULL,
  "nhc" text NOT NULL,
  "nombre" text NOT NULL,
  "apellidos" text NOT NULL,
  "fecha_nacimiento" text NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "procedimientos" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "especialidad" text NOT NULL,
  "nombre_procedimiento" text NOT NULL,
  PRIMARY KEY ("id")
);

CREATE TABLE "registros_hospital" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "intervencion_id" integer NOT NULL,
  "ruta_pdf" text NOT NULL,
  "fecha" text NOT NULL,
  "usuario" text,
  PRIMARY KEY ("id")
);

CREATE TABLE "tabla_maestra" (
  "referencia" text,
  "nombre" text,
  "especialidad" text,
  "tipo" text,
  "lateralidad" text,
  "material" text,
  "fabricante" text,
  "gtin" text,
  "tamano" text,
  "modelo" text,
  PRIMARY KEY ("referencia")
);

CREATE TABLE "zonas_anatomicas" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY,
  "especialidad" text NOT NULL,
  "zona" text NOT NULL,
  PRIMARY KEY ("id")
);

COMMIT;
